"""initial_schema

Revision ID: 27db3a4305d2
Revises: 
Create Date: 2026-06-15 14:12:36.895342

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '27db3a4305d2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sources',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('base_url', sa.String(length=512), nullable=False),
    sa.Column('scraper_class', sa.String(length=255), nullable=True, comment='Ruta Python al scraper, ej: app.scrapers.computrabajo.ComputrabajoScraper'),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sources'))
    )
    op.create_index(op.f('ix_sources_slug'), 'sources', ['slug'], unique=True)
    op.create_table('users',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('alerts',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('filters', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Filtros: keywords, location, modality, seniority, salary_min, etc.'),
    sa.Column('frequency', sa.Enum('instant', 'daily', 'weekly', name='alertfrequency', create_constraint=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_alerts_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_alerts'))
    )
    op.create_index('ix_alerts_user_active', 'alerts', ['user_id', 'is_active'], unique=False)
    op.create_table('offers',
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=False),
    sa.Column('fingerprint', sa.String(length=64), nullable=False, comment='Hash SHA-256 de campos clave para deduplicación cross-source'),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('normalized_title', sa.String(length=500), nullable=True),
    sa.Column('company', sa.String(length=255), nullable=False),
    sa.Column('normalized_company', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('modality', sa.Enum('remote', 'hybrid', 'on_site', 'unknown', name='modality', create_constraint=True), nullable=False),
    sa.Column('job_type', sa.Enum('full_time', 'part_time', 'contract', 'freelance', 'internship', 'temporary', 'unknown', name='jobtype', create_constraint=True), nullable=False),
    sa.Column('seniority', sa.Enum('intern', 'junior', 'mid', 'senior', 'lead', 'director', 'unknown', name='seniority', create_constraint=True), nullable=False),
    sa.Column('status', sa.Enum('active', 'expired', 'filled', 'removed', name='offerstatus', create_constraint=True), nullable=False),
    sa.Column('salary_min', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('salary_max', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('salary_currency', sa.String(length=3), nullable=True),
    sa.Column('url', sa.String(length=1024), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], name=op.f('fk_offers_source_id_sources'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_offers')),
    sa.UniqueConstraint('fingerprint', name='uq_offers_fingerprint'),
    sa.UniqueConstraint('source_id', 'external_id', name='uq_offers_source_external')
    )
    op.create_index('ix_offers_company', 'offers', ['company'], unique=False)
    op.create_index('ix_offers_location', 'offers', ['location'], unique=False)
    op.create_index('ix_offers_modality_job_type', 'offers', ['modality', 'job_type'], unique=False)
    op.create_index('ix_offers_seniority', 'offers', ['seniority'], unique=False)
    op.create_index(op.f('ix_offers_source_id'), 'offers', ['source_id'], unique=False)
    op.create_index(op.f('ix_offers_status'), 'offers', ['status'], unique=False)
    op.create_index('ix_offers_status_published', 'offers', ['status', 'published_at'], unique=False)
    op.create_table('profiles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=True),
    sa.Column('headline', sa.String(length=300), nullable=True),
    sa.Column('cv_text', sa.Text(), nullable=True),
    sa.Column('cv_embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True, comment='Embedding del CV para matching semántico'),
    sa.Column('skills', postgresql.ARRAY(sa.String(length=100)), nullable=True),
    sa.Column('preferred_modalities', postgresql.ARRAY(sa.Enum('remote', 'hybrid', 'on_site', 'unknown', name='modality')), nullable=True),
    sa.Column('preferred_locations', postgresql.ARRAY(sa.String(length=100)), nullable=True),
    sa.Column('min_salary', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('seniority', sa.Enum('intern', 'junior', 'mid', 'senior', 'lead', 'director', 'unknown', name='seniority', create_constraint=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_profiles_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_profiles')),
    sa.UniqueConstraint('user_id', name=op.f('uq_profiles_user_id'))
    )
    op.create_index('ix_profiles_seniority', 'profiles', ['seniority'], unique=False)
    op.create_table('scrape_runs',
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'running', 'completed', 'failed', name='scraperunstatus', create_constraint=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('offers_found', sa.Integer(), nullable=False),
    sa.Column('offers_new', sa.Integer(), nullable=False),
    sa.Column('offers_updated', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], name=op.f('fk_scrape_runs_source_id_sources'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scrape_runs'))
    )
    op.create_index('ix_scrape_runs_source_status', 'scrape_runs', ['source_id', 'status'], unique=False)
    op.create_index('ix_scrape_runs_started_at', 'scrape_runs', ['started_at'], unique=False)
    op.create_table('applications',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('offer_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'applied', 'interview', 'offer', 'rejected', 'withdrawn', name='applicationstatus', create_constraint=True), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('applied_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['offer_id'], ['offers.id'], name=op.f('fk_applications_offer_id_offers'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_applications_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_applications')),
    sa.UniqueConstraint('user_id', 'offer_id', name='uq_applications_user_offer')
    )
    op.create_index('ix_applications_applied_at', 'applications', ['applied_at'], unique=False)
    op.create_index('ix_applications_user_status', 'applications', ['user_id', 'status'], unique=False)
    op.create_table('salary_reports',
    sa.Column('offer_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True, comment='Null = reporte anónimo'),
    sa.Column('salary_min', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('salary_max', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('reported_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['offer_id'], ['offers.id'], name=op.f('fk_salary_reports_offer_id_offers'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_salary_reports_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_salary_reports'))
    )
    op.create_index('ix_salary_reports_offer', 'salary_reports', ['offer_id'], unique=False)
    op.create_index('ix_salary_reports_reported_at', 'salary_reports', ['reported_at'], unique=False)
    op.create_table('saved_offers',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('offer_id', sa.UUID(), nullable=False),
    sa.Column('saved_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['offer_id'], ['offers.id'], name=op.f('fk_saved_offers_offer_id_offers'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_saved_offers_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_saved_offers')),
    sa.UniqueConstraint('user_id', 'offer_id', name='uq_saved_offers_user_offer')
    )
    op.create_index('ix_saved_offers_user_saved_at', 'saved_offers', ['user_id', 'saved_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_saved_offers_user_saved_at', table_name='saved_offers')
    op.drop_table('saved_offers')
    op.drop_index('ix_salary_reports_reported_at', table_name='salary_reports')
    op.drop_index('ix_salary_reports_offer', table_name='salary_reports')
    op.drop_table('salary_reports')
    op.drop_index('ix_applications_user_status', table_name='applications')
    op.drop_index('ix_applications_applied_at', table_name='applications')
    op.drop_table('applications')
    op.drop_index('ix_scrape_runs_started_at', table_name='scrape_runs')
    op.drop_index('ix_scrape_runs_source_status', table_name='scrape_runs')
    op.drop_table('scrape_runs')
    op.drop_index('ix_profiles_seniority', table_name='profiles')
    op.drop_table('profiles')
    op.drop_index('ix_offers_status_published', table_name='offers')
    op.drop_index(op.f('ix_offers_status'), table_name='offers')
    op.drop_index(op.f('ix_offers_source_id'), table_name='offers')
    op.drop_index('ix_offers_seniority', table_name='offers')
    op.drop_index('ix_offers_modality_job_type', table_name='offers')
    op.drop_index('ix_offers_location', table_name='offers')
    op.drop_index('ix_offers_company', table_name='offers')
    op.drop_table('offers')
    op.drop_index('ix_alerts_user_active', table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_sources_slug'), table_name='sources')
    op.drop_table('sources')
    # ### end Alembic commands ###